### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by MrAkells** [asiekierka/FoamFix17#2]
I have a skin with the "Alex" model. I use the latest version of the mod, 1.0.0. After reconnecting to a world or server, my arm gets fatter. Like it's a "Steve" model. Only restarting the client helps. Tested with one foamfix.

![2022-01-24_05-30](https://user-images.githubusercontent.com/64635280/150708113-1a958c45-95ed-455b-a5e4-a5b64d909dd0.png)
![2022-01-24_05-29](https://user-images.githubusercontent.com/64635280/150708112-84f07962-d5fe-48b1-8225-faa4ef5b00e7.png)

**Comment by makamys** [comment]
Seems to be fixed as of 1.0.1. The relevant Ears issue is https://github.com/unascribed/Ears/issues/45
