### ISSUE TITLE
[Feature Request] Back port new version's entity collision algorithm

### ISSUE THREAD

**Issue by kappa-maintainer** [asiekierka/FoamFix17#3]
Many mods that add grass path to 1.7.10 found walking from paths to slabs is not as easy as 1.9+. Changing step height can fix it, but raised the problem in entity movement algorithm. For more details, visit [this issue](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/51).

**Comment by Roadhog360** [comment]
This could possibly reopened, there is a bug with EFR's implementation. I have been unable to solve it.
